### ISSUE TITLE
Unable to export as txt

### ISSUE THREAD

**Issue by Xenchrarr** [Secretmud/addressbook#11]
`Traceback (most recent call last):
  File "main.py", line 254, in <module>
    m.main(sys.argv[1:])
  File "main.py", line 249, in main
    m.start()
  File "main.py", line 63, in start
    self.export_data()
  File "main.py", line 96, in export_data
    de.export_txt()
  File "........../Modules/data.py", line 88, in export_txt
    writer = out.writer(out, lineterminator='\n')
`

**Comment by Secretmud** [comment]
This issue is now solved
