### ISSUE TITLE
Bug when starting from scratch

### ISSUE THREAD

**Issue by Xenchrarr** [Secretmud/addressbook#2]
With the lastes update, it will not create the table "book"

`Traceback (most recent call last):
  File "main.py", line 56, in <module>
    m.start()
  File "main.py", line 29, in start
    self.update_data()
  File "main.py", line 51, in update_data
    da.save_data(name, phoneNumber, address, email)
  File "/Users/emil/addressbook/Modules/data.py", line 32, in save_data
    VALUES(?, ?, ?, ?)''', (name, phoneNumber, address, email))
`

**Comment by Secretmud** [comment]
Fixed :)!
